sonar.projectKey=ccvv
sonar.projectName=ccvv
sonar.sources=core/ccvv-lib/src,core/ccvv-cli/src
sonar.language=rust
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_e119044bff759c93543c47f50345b5987fbfe2e7
